num1 = int(input('Enter the first number: '))
num2 = int(input('Enter the second number: '))
print(f'\nAddition: {num1 + num2}')
print(f'Subtraction: {num1 - num2}')
print(f'Multiplication: {num1 * num2}')
print('Cannot divide by zero.' if not(num2) else f'Division: {num1 / num2}')
